from matplotlib.colors import to_rgb
import math

# Parameters
GAME_TITLE = 'Lines of Empire'

INITIAL_SCREEN_WIDTH = 1280
INITIAL_SCREEN_HEIGHT = 720

MAP_SCALE = '50m' # Options are: 10m, 50m, 110m, from Natural Earth

INITIAL_LON = 15.0
INITIAL_LAT = 50.0
INITIAL_ZOOM = 300.0

CAMERA_SPEED = 60.0 # degrees per second
ZOOM_SPEED = 1.5
FAST_SPEED_MULTIPLIER = 3.0
SLOW_SPEED_MULTIPLIER = 0.25

MIN_ZOOM_MULTIPLIER = 0.35
MAX_ZOOM_MULTIPLIER = 8

# Map colors and styling
#LAND_COLOR = to_rgb('#d8c99b')
LAND_COLOR = to_rgb('#d8c8a8')
#OCEAN_COLOR = to_rgb('#557c7a')
OCEAN_COLOR = to_rgb('#588080')
COAST_COLOR = to_rgb('#282620')
OUTSIDE_COLOR = to_rgb('#18191b')
BORDER_COLOR = to_rgb('#635441')
VORONOI_EDGE_COLOR = to_rgb('#282828')
VORONOI_SEED_COLOR = to_rgb('#ff0000')

COAST_THICKNESS = 2.0
RIVER_THICKNESS = 1.25
BORDER_THICKNESS = 1.0
#PROVINCE_THICKNESS = 0.75
HORIZON_THICKNESS = 2.0
VORONOI_EDGE_THICKNESS = BORDER_THICKNESS
VORONOI_SEED_SIZE = 8.0

CITY_SYMBOL_RADIUS = math.radians(0.2)

OCEAN_SEGMENTS = 256
MAX_VECTOR_ARC_DEGREES = 2.0
MAX_VECTOR_ARC = math.radians(MAX_VECTOR_ARC_DEGREES)
